apiVersion: v2
name: onecx-tenant-ui
version: 0.0.0
description: onecx-tenant UI
home: https://github.com/onecx/onecx-tenant-ui
keywords:
  - tenant
sources:
  - https://github.com/onecx/onecx-tenant-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
